#- include: leftwm.yml

- include: i3_install.yml

- name: Install desktop components
  ansible.builtin.apt:
    name: "{{ item }}"
    update_cache: true
  become: true
  with_items:
    - rofi
    - open-vm-tools
    - feh

#- include: picom_install.yml
- include: alttab_install.yml

- name: Ensure wallpaper folder exists
  ansible.builtin.file:
    path: "{{ xdg_data_home }}/wallpapers/"
    state: directory

- name: Download wallpaper
  ansible.builtin.get_url:
    url: "{{ wallpaper_url }}"
    dest: "{{ xdg_data_home }}/wallpapers/"
  